### ISSUE TITLE
it does not load image until you scroll when refresh/reload page

### ISSUE THREAD

**Issue by CydGoblin** [callmecavs/layzr.js#39] opened 2015-06-15 18:02 UTC
![lazy](https://cloud.githubusercontent.com/assets/4932347/8166615/2c0eae80-1356-11e5-961e-80460444e104.gif)

**Comment by callmecavs** [comment] 2015-06-15 19:07
hmm. perhaps I need to call `update` directly in the `create` method? right now I'm requesting the scroll, which in theory should call the update function, but perhaps an animation frame is still running from before the refresh?

**Comment by zslabs** [comment] 2015-07-09 19:37
Does this question go along with dynamic content brought in via AJAX, backbone or React? I'm currently using another lib that triggers on scroll for the lookup, but would prefer for it to do these checks with rAF regardless of interaction from the end-user (a scroll).

**Comment by CydGoblin** [comment] 2015-07-10 02:12
@zslabs nop, just plain old html and css

**Comment by callmecavs** [comment] 2015-07-10 02:23
@zslabs what @Turqueso said :+1:

**Comment by callmecavs** [comment] 2015-07-10 02:25
@Turqueso i think the fix for this may be as simple as changing line 7 from:

``` javascript
this._lastScroll = 0;
```

to:

``` javascript
this._lastScroll = window.scrollY || window.pageYOffset;
```

the problem you're experiencing is likely caused by the library assuming that you haven't scrolled at all (window.scrollY = 0) when the instance is created.  which is not the case if you're refreshing.  ill have some time to test it this weekend

**Comment by callmecavs** [comment] 2015-07-16 15:31
@Turqueso ping

**Comment by CydGoblin** [comment] 2015-07-17 21:31
@callmecavs I'm trying to recreate the problem but it's working now... maybe i did something weird the first time or some other jquery messed with it?

**Comment by callmecavs** [comment] 2015-07-18 13:42
no problem, let me know if you have any luck recreating it. will close this for now

**Closed as completed by callmecavs** 2015-07-18 13:42 UTC

**Comment by OriginalEXE** [comment] 2016-01-20 16:40
I'm commenting here because the issue is kinda related.

On your demo website, the images do not show up until the scroll/resize event is triggered. You can check the video of the issue here (sorry for the crappy quality): https://dl.dropboxusercontent.com/u/20590482/GitHub%20Issues/Lazyr.js/lazyr%20issue.mp4

**Comment by callmecavs** [comment] 2016-01-20 16:47
@OriginalEXE using the new API, all you have to do is call `check` when the page loads. this will make sure any images in the viewport on page load are loaded instantly.

example code:

``` es6
// create instance
const instance = Layzr()

// start it up
instance
  .update()         // track initial elements
  .check()          // check initial elements
  .handlers(true)   // bind scroll and resize handlers
```

let me know if that works for you

**Comment by OriginalEXE** [comment] 2016-01-20 16:50
I haven't actually used this anywhere (yet, waiting for picture support :)), I just checked your demo and noticed the said issue, so just thought I should mention it :)

**Comment by callmecavs** [comment] 2016-01-20 17:15
@OriginalEXE im going to add the above to the demo :wink: right now I'm not calling `check` haha. thanks for pointing it out :beers:
